name: Release

on:
  push:
    branches:
      - main
      - beta
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - CONTRIBUTING.md
      - renovate.json
      - ".github/workflows/**"
      - .releaserc.yml
      - .scalafix.conf
      - .scalafmt.conf
      - "package*.json"
      - codecov.yml
  workflow_dispatch:

jobs:
  release:
    name: Release on Maven Central and GitHub
    runs-on: ubuntu-20.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala environment
        uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17
      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Publish plugin
        id: publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      - name: Generate scaladoc
        if: steps.publish.outputs.prerelease == 0
        run: sbt doc
      - name: Publish on GitHub Pages
        if: steps.publish.outputs.prerelease == 0
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/scala-3.2.1/api